# Generated by Django 2.2 on 2020-01-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='todo.List')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='todo.List')),
            ],
        ),
    ]
